### ISSUE TITLE
Tilda

### ISSUE THREAD

**Issue by davedorm** [jan-warchol/selenized#26]
Brilliant! But I use Tilda as my main terminal. Can you work your magic there?

**Comment by jan-warchol** [comment]
Thanks! I should be able to add support for Tilda. Could you send me an
example configuration file with some other palette?

6 sty 2017 07:10 "Manah Manah" <notifications@github.com> napisał(a):

**Comment by davedorm** [comment]
Yep. Here you go!
[config_2.txt](https://github.com/jan-warchol/selenized/files/691837/config_2.txt)

**Comment by jan-warchol** [comment]
Thanks! I see that Tilda stores color configuration in non-conventional way, so it may be a couple days until I'll have enough time to do this properly, but I will do it :-)

**Comment by jan-warchol** [comment]
This pull request should do it: https://github.com/jan-warchol/selenized/pull/27

@davedorm can you test it please?

**Comment by jan-warchol** [comment]
@davedorm ping :) Did you try the config from `tilda-support` branch?

**Comment by dngray** [comment]
I'm not sure that Tilda is actually maintained much anymore https://github.com/lanoxx/tilda

If you have a look plenty of PRs and bugs and no commits.

I think most people that want a drop-down terminal like that these days are using Tilix. Apparently it also has  "Quake Mode" https://github.com/gnunn1/tilix/wiki/Quake-Mode

**Comment by jan-warchol** [comment]
Well, when I checked today I saw some activity in tilda repository, and also the config seems to work with tilda I've installed - so I'm going to merge the PR fwiw ;)

**Comment by dngray** [comment]
Seems development on this has restarted. There wasn't any commits between [Dec 29, 2018 and Oct 27, 2019](https://github.com/lanoxx/tilda/commits/master?after=e92175ae58a2d257034a65a450c1d4208de81a77+34), but now there is regular activity.
