### ISSUE TITLE
Vim suggestions look bad

### ISSUE THREAD

**Issue by Envielox** [jan-warchol/selenized#33]
![screenshot2](https://cloud.githubusercontent.com/assets/1052735/23794238/778feaae-058f-11e7-9743-8722e50ce6d2.png)

**Comment by dngray** [comment]
I was looking at this today. and I agree it's terrible, we should select a better color than pink:

![1572254112](https://user-images.githubusercontent.com/48640805/67666455-be391000-f963-11e9-825c-e935c33514f0.png)
