### ISSUE TITLE
Tilix support 

### ISSUE THREAD

**Issue by poeyashi** [jan-warchol/selenized#37]
It would be great to have support for Tilix terminal. 

To use this theme in Tilix, you need to do something like: 

1. `dconf dump /com/gexperts/Tilix/ > tilix.conf`
2. Edit tilix.conf and replace options: 
```
foreground-color='#374a50'
palette=['#ebe6c9', '#d5252f', '#4a9300', '#b08b00', '#0074d6', '#cd4b9a', '#009f92', '#7d8782', '#cecaad','#cc1729', '#428b00', '#a78300', '#006dce', '#c44392', '#00978a', '#192c31']
background-color='#fefadc'
```
3. Load configuration again with:
`dconf load /com/gexperts/Tilix/ < tilix.conf`

I don't know currently how to make it better, it's just a quick and dirty configuration that works.

**Comment by poeyashi** [comment]
Seems like it should be enough to put gist content in ~/.config/tilix/schemes/selenized.json. 

https://gist.github.com/poeyashi/95058e97c23f09078ae9115eae77a8d8

**Comment by jan-warchol** [comment]
Fixed in !40

**Comment by jan-warchol** [comment]
Fixed in https://github.com/jan-warchol/selenized/pull/40
