### ISSUE TITLE
Support for Kitty terminal

### ISSUE THREAD

**Issue by kristijanhusak** [jan-warchol/selenized#51]
Hi,

can you add support for [Kitty](https://github.com/kovidgoyal/kitty) terminal?

**Comment by dngray** [comment]
Perhaps leave a config here, I don't use Kitty myself personally, but instructions or even better PR would be nice :)

It's fairly easy to make a [template](https://github.com/jan-warchol/selenized/tree/master/utils/templates) using [evaluate_template.py](https://github.com/jan-warchol/selenized/tree/master/utils#generating-config-files). You can see an [example template](https://github.com/jan-warchol/selenized/blob/master/utils/templates/template-test.example.template).

**Comment by dngray** [comment]
@kristijanhusak tell me what you think.

**Comment by kristijanhusak** [comment]
@dngray looks good, thanks!
