### ISSUE TITLE
Include a LICENSE

### ISSUE THREAD

**Issue by dngray** [jan-warchol/selenized#56]
This should include a LICENSE even if it's something as simple as MIT license, (that's what [solarized has](https://github.com/altercation/solarized/blob/master/LICENSE))

**Comment by ianchanning** [comment]
Yes - the problem is that without the licence it's assumed that no-one can use it

**Comment by dngray** [comment]
@jan-warchol could you take a look at this. Thanks.

**Comment by micharbet** [comment]
@jan-warchol 
In file CONTRIBUTING.md you mention that people are welcome to adjust the theme. The License would be very welcomed. E.g. I would like to include your wonderful work into my project and doing it without an explicit license is not right.

Thank you!

**Comment by dngray** [comment]
I think an MIT style license is appropriate... maybe i'lll put a PR in and hope that he has time to click the "merge" button haha.

**Comment by dngray** [comment]
https://github.com/jan-warchol/selenized/pull/96

**Comment by TeddyDD** [comment]
Ummm, bump @jan-warchol 😊

Seriously tho, while colors itself can't be licensed afaik, we are (legally) not allowed to do anything with code and generated configs.
