### ISSUE TITLE
Vim: style remaining default groups

### ISSUE THREAD

**Issue by jan-warchol** [jan-warchol/selenized#67]
#59 implemented minimal styling necessary to use selenized with Vim, but some highlight groups remained unstyled (they are listed [at the end of the template file](https://github.com/jan-warchol/selenized/blob/faec8b8aa525027e660c052d4247bf4557c897e5/vim/_hl_groups.colortemplate#L91)).

Remember to test the results in terminal&GUI, vim&neovim.

**Comment by dngray** [comment]
I might have a go at this and see how I go
