### ISSUE TITLE
Vim  mapping colours to highlight groups

### ISSUE THREAD

**Issue by fladd** [jan-warchol/selenized#69]
The current mapping from the colours to their highlight groups does not seem to be optimal. I would have expected Selenized to look very similar to Solarized (just with better contrast and slightly different shades of the colours), but the syntax colours are completely shuffled around.

![image](https://user-images.githubusercontent.com/2971539/76639134-e493cc80-654d-11ea-8494-209f89a7fac1.png)
(left: Solarized8, right: Selenized)

Also, something weird is going on with the status line.

**Comment by jan-warchol** [comment]
Hello @fladd,

this opens a very interesting topic. To be honest, I don't particularly like Solarized's choice of token-color mappings (in particular I think using green for keywords is a bad choice). However, I'm not completely satisfied with current selenized coloring and I indeed intend to change it at least a bit. 

There is also the issue with number of colors available: solarized uses 8 "accent" colors, but it requires [an ugly hack that selenized aims to avoid](https://github.com/jan-warchol/selenized/blob/master/whats-wrong-with-solarized.md#problems-with-implementation). So, full solarized compatibility is impossible (at least with coloring based on terminal's ANSI codes).

My question is: is having selenized mimic solarized's syntax coloring a must-have for you (and any other people)? Would you be okay with some kind of middle ground?

(PS I'm not talking about the status line, that one is definitely a bug.)

**Comment by jan-warchol** [comment]
PS could you send me the source used to make the screenshots? I'm surprised that class name was colored green, it's supposed to be pink. I'd like to inspect it.

**Comment by fladd** [comment]
@jan-warchol: Thanks for the quick response.

 I think Solarized's colour mappings are generally pretty well chosen. Something approaching this at least should be welcome by most people I think.

I map Python class names to `Type` in my .vimrc, because by default, Vim does not dissociate between class names and function names. I think this is a pretty common thing to do. Unfortunately, in Selenized, `Type` has the same colour as strings.

**Comment by jan-warchol** [comment]
> @jan-warchol: Thanks for the quick response.
> 
> I think Solarized's colour mappings are generally pretty well chosen. Something approaching this at least should be welcome by most people I think.

Hmm. I'm close to being convinced. Would you be able to help me with testing?

Also, @dngray, what do you think? Have you started any work on #67?

> I map Python class names to `Type` in my .vimrc, because by default, Vim does not dissociate between class names and function names. I think this is a pretty common thing to do. Unfortunately, in Selenized, `Type` has the same colour as strings.

Ah, ok. Thanks for explaining.

**Comment by fladd** [comment]
> Hmm. I'm close to being convinced. Would you be able to help me with testing?
Sure.

**Comment by dngray** [comment]
> Also, @dngray, what do you think? Have you started any work on #67?

No I have not yet, been meaning to get to it this week along with `:set spell` highlights.

**Comment by jan-warchol** [comment]
Okay, so I suggest the following plan:
* I'll rework highlighting of syntax groups to be more like solarized
* I like current syntax highlighting so I'll use it as a basis for another theme, most probably full-color version of [limestone](https://github.com/jan-warchol/limestone-colors) (I need to add some screenshots there...)
* unstyled elements mentioned in #67 are almost exclusively interface elements, so I'll leave them to @dngray 
* we'll need some code samples for testing. I'll setup a repo and I count on @fladd's help here :-)

**Comment by jan-warchol** [comment]
@fladd Here's the repo with samples for testing; feel free to comment or submit your own samples. https://github.com/jan-warchol/highlighting-code-samples

**Comment by dngray** [comment]
> unstyled elements mentioned in #67 are almost exclusively interface elements, so I'll leave them to @dngray

I'll get on that this week.

**Comment by jan-warchol** [comment]
Closed via #70, but part of the discussion is continued in #74.
