### ISSUE TITLE
evaluate_template.py syntax errors

### ISSUE THREAD

**Issue by dngray** [jan-warchol/selenized#79]
Seems to be a problem with the evaluate_template.py script, it's stopping me from testing https://github.com/jan-warchol/selenized/pull/31

```
$ python evaluate_template.py selenized_dark.py putty.template
  File "/selenized/utils/evaluate_template.py", line 63
    print '' # section separator
          ^
SyntaxError: Missing parentheses in call to 'print'. 
Did you mean print('' # section separator)?
```

**Comment by jan-warchol** [comment]
Thanks for checking on this. I think this branch is so old that it doesn't include porting to python 3. Also, templating variable names were updated in the meantime.
I'll rebase and push to `putty-rebased`.

**Comment by dngray** [comment]
Sure, this fixed it.
